version: "3.9"

services:
  gridstats-backend:
    image: claudio08092002/gridstats:latest
    container_name: gridstats-backend
    environment:
      - FASTF1_CACHE=/data/fastf1_cache
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
      - PREWARM_SEASONS=2024,2025
      - ENABLE_SPRINT_POINTS=1
      - SEASON_MEM_TTL=21600
    volumes:
      - fastf1_cache:/data/fastf1_cache
      # REMOVED: season_cache and tracks_cache volumes
      # These must be bundled IN the Docker image, not mounted as volumes
      # Mounting them would overwrite the cache files with empty directories
    ports:
      - "7500:8000"
    restart: unless-stopped

  gridstats-frontend:
    image: claudio08092002/gridstats-frontend:latest
    container_name: gridstats-frontend
    ports:
      - "7501:80"
    restart: unless-stopped

volumes:
  fastf1_cache:
  # REMOVED: season_cache volume - not needed
