version: "3.9"

services:
  gridstats-backend:
    image: claudio08092002/gridstats:latest
    container_name: gridstats-backend
    environment:
      - FASTF1_CACHE=/data/fastf1_cache
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
    volumes:
      - fastf1_cache:/data/fastf1_cache
      - season_cache:/app/app/season_cache
    ports:
      - "7500:8000"
    restart: unless-stopped

  gridstats-frontend:
    image: claudio08092002/gridstats-frontend:latest
    container_name: gridstats-frontend
    ports:
      - "7501:80"
    restart: unless-stopped

volumes:
  fastf1_cache:
  season_cache:
