version: "3.9"

services:
  backend:
    image: claudio08092002/gridstats:latest         # Backend-Image aus Registry
    container_name: gridstats-backend
    environment:
      - FASTF1_CACHE=/data/fastf1_cache
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
    volumes:
      - fastf1_cache:/data/fastf1_cache
      - season_cache:/app/app/season_cache
    expose:
      - "8000"
    restart: unless-stopped

  frontend:
    image: claudio08092002/gridstats-frontend:latest # Frontend-Image aus Registry
    container_name: gridstats-frontend
    ports:
      - "80:80"                                      # oder weglassen, wenn dein externes Proxy-GUI mapped
    restart: unless-stopped

volumes:
  fastf1_cache:
  season_cache:
